import { Link, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, Bot, Radio } from 'lucide-react'
import { operationsApi, responsesApi, specsApi } from '../services/api'
import type { Operation, ResponseConfig, Spec } from '../types'
import ResponseConfigList from './ResponseDesigner/ResponseConfigList'

export default function OperationRecordedResponsesPage() {
    const { operationId } = useParams<{ operationId: string }>()

    const { data: operation, isLoading: opLoading } = useQuery<Operation>({
        queryKey: ['operation', operationId],
        queryFn: () => operationsApi.get(operationId!),
        enabled: !!operationId,
    })

    const { data: spec } = useQuery<Spec>({
        queryKey: ['spec', operation?.specId],
        queryFn: () => specsApi.get(operation!.specId),
        enabled: !!operation?.specId,
    })

    const { data: responses, isLoading: respLoading } = useQuery<ResponseConfig[]>({
        queryKey: ['responses', operationId],
        queryFn: () => responsesApi.listByOperation(operationId!),
        enabled: !!operationId,
    })

    const recordedResponses = (responses || []).filter((config) => config.recorded)
    const isLoading = opLoading || respLoading

    if (isLoading) {
        return (
            <div className="p-8">
                <div className="animate-pulse space-y-4">
                    <div className="h-8 bg-gray-200 dark:bg-slate-800 rounded w-48"></div>
                    <div className="h-32 bg-gray-200 dark:bg-slate-800 rounded-xl"></div>
                </div>
            </div>
        )
    }

    if (!operation) {
        return (
            <div className="p-8">
                <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700 dark:bg-red-950/40 dark:border-red-900/40 dark:text-red-300">
                    Operation not found
                </div>
            </div>
        )
    }

    return (
        <div className="p-8 space-y-6">
            <div className="space-y-4">
                <Link
                    to={`/operations/${operationId}`}
                    className="inline-flex items-center text-sm text-gray-500 dark:text-slate-400 hover:text-gray-700 dark:hover:text-slate-200"
                >
                    <ArrowLeft className="w-4 h-4 mr-1" />
                    Back to Operation
                </Link>

                <div className="flex flex-wrap items-start justify-between gap-4">
                    <div>
                        <h1 className="text-2xl font-semibold text-gray-900 dark:text-slate-100">
                            Generated Responses
                        </h1>
                        <p className="text-sm text-gray-500 dark:text-slate-400 mt-2">
                            Replayable responses captured by proxy fallback or generated by AI for this operation.
                        </p>
                    </div>
                    <div className="flex flex-wrap items-center gap-2">
                        {spec?.mode === 'proxy' && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300">
                                <Radio className="w-3 h-3 animate-pulse" />
                                Recording active
                            </span>
                        )}
                        {spec?.mode === 'ai' && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-900/40 dark:text-fuchsia-300">
                                <Bot className="w-3 h-3" />
                                AI fallback active
                            </span>
                        )}
                        <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-700 dark:bg-slate-800 dark:text-slate-300">
                            {recordedResponses.length} recorded
                        </span>
                        <div className="rounded-xl border border-gray-200 dark:border-slate-800 px-4 py-2 bg-white dark:bg-slate-900 text-sm text-gray-600 dark:text-slate-300">
                            <span className="font-semibold text-gray-900 dark:text-slate-100 mr-2">{operation.method}</span>
                            <span className="font-mono">{operation.path}</span>
                        </div>
                    </div>
                </div>
            </div>

            <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-gray-200 dark:border-slate-800">
                <div className="p-6 border-b border-gray-200 dark:border-slate-800">
                    <h2 className="text-lg font-semibold text-gray-900 dark:text-slate-100">Generated Responses</h2>
                    <p className="text-sm text-gray-500 dark:text-slate-400 mt-1">
                        Edit or remove replayable responses generated by proxy or AI fallback without crowding the main operation page.
                    </p>
                </div>

                <ResponseConfigList
                    operationId={operationId!}
                    configs={recordedResponses}
                    emptyTitle="No generated responses yet"
                    emptyDescription="Use AI or proxy mode on the parent spec and send requests through this operation to capture replayable responses here."
                    editSource="recorded"
                />
            </div>
        </div>
    )
}
